@startuml Factory
title Factory pattern (IFactory<T>)
interface "IFactory<T>" as IFactory_T {
    +create() : T
}

interface IVehicle {}

class Motorcycle {
    +ride() : void
}

class Car {
    +drive() : void
}

class Truck {
    +haul() : void
}


class VehicleFactory {
    +create(kind: String) : IVehicle
}

IFactory_T <|.. VehicleFactory
VehicleFactory --> IVehicle : returns
Motorcycle <|.. IVehicle
Car <|.. IVehicle
Truck <|.. IVehicle

@enduml